spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri : https://github.com/BhargaviKavalanekar/Case-Study_Deals_and_Coupons
server:
  port: 20005

